version: '3.8'
services:
    boilerplate:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: ${NODE_ENV}
        image: boilerplate:0.1
        ports:
            - '3000:3000'
        volumes:
            - ~/Documents/boilerplate/logs/pm2:/app/logs/pm2
        environment:
            - NODE_ENV=${NODE_ENV}

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - ~/Documents/boilerplate/redis_data:/data

volumes:
    redis_data:
